spring:
  application:
    name: dailyApi
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lmy?timezone=UTC
    username: root
    password: 20041129gj

mybatis:
  mapper-locations: classpath:mapper/*.xml

ai-chat:
  ais:
    deepseek:
      name: deepseek
      url: https://api.deepseek.com/chat/completions
      model: deepseek-chat
      key: key
    kimi:
      name: kimi
      url: https://api.moonshot.cn/v1/chat/completions
      model: moonshot-v1-8k
      key: key

#deepseek_key=DEEPSEEK_KEY
#deepseek_url=https://api.deepseek.com/chat/completions
#deepseek_model=deepseek-chat
#kimi_key=KIMI_KEY
#kimi_url=https://api.moonshot.cn/v1/chat/completions
#kimi_model=moonshot-v1-8k