spring:
  application:
    name: dailyApi
  config:
    import: properties.yml
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_user?timezone=UTC
    username: root
    password: 050109
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 050109
      database: 0

mybatis:
  mapper-locations: classpath:mapper/*.xml

ai-chat:
  ais:
    deepseek:
      name: ${ai.deepseek.name}
      url: ${ai.deepseek.url}
      model: ${ai.deepseek.model}
      key: ${ai.deepseek.key}
    kimi:
      name: ${ai.kimi.name}
      url: ${ai.kimi.url}
      model: ${ai.kimi.model}
      key: ${ai.kimi.key}

meitu:
  meitus:
    cutout:
      key: ${meitu.meitu_cutout.key}
      secret: ${meitu.meitu_cutout.secret}
    common:
      key: ${meitu.meitu_common.key}
      secret: ${meitu.meitu_common.secret}

#deepseek_key=DEEPSEEK_KEY
#deepseek_url=https://api.deepseek.com/chat/completions
#deepseek_model=deepseek-chat
#kimi_key=KIMI_KEY
#kimi_url=https://api.moonshot.cn/v1/chat/completions
#kimi_model=moonshot-v1-8k